

rule hadd:
    input:
        rules.samples.output
    output:
        "ntupleOut.root"
    log:
        "logs/root/hadd.log"
    wrapper:
        "master/phys/root/hadd"
        
rule samples:
    output:
        expand("ntuple{n}.root", n=range(4))
    script:
        "generate.py"